### ISSUE TITLE
Thank you and Dockerfile

### ISSUE THREAD

**Issue by mohsinhijazee** [jamesmoriarty/forward-proxy#4]
Thank you for writing this small bare bone to the essentials forward proxy. I learned a lot from it. 

Further, I guess it would be nice if there's a `Dockerfile` and the image is pulled to docker so that ruby is not required to run it. I will see if I can spare some time to submit a PR.

**Comment by jamesmoriarty** [comment]
Thanks for the message. Would be happy to include a `Dockerfile` and add an alternative usage method via Docker.
